version: 1
loggers:
    l3Clos :
        level: DEBUG
        handlers: [console, file] 
    report : 
        level: INFO
        handlers: [console, file] 
    ztp : 
        level: INFO
        handlers: [console, file] 
    rest : 
        level: DEBUG
        handlers: [console, file] 
    writer : 
        level: INFO
        handlers: [console, file] 
    devicePlugin : 
        level: DEBUG
        handlers: [console, file] 
    trapd : 
        level: INFO
        handlers: [console, file] 
    dao : 
        level: INFO
        handlers: [console, file] 
    loader : 
        level: INFO
        handlers: [console, file] 
    overlay : 
        level: INFO
        handlers: [console, file] 
formatters:
    detailed:
        format: '%(asctime)s [%(name)-12s] [%(levelname)-8s] [%(thread)8x] %(message)s'
handlers:
    console:
        class: logging.StreamHandler
        formatter: detailed
    file:
        filename: '%(fullPath)openclos-%(appName).log'
        class: logging.handlers.RotatingFileHandler
        formatter: detailed
        maxBytes: 1048576
        backupCount: 0
